# Generated by Django 4.0.1 on 2022-01-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_projeto', models.CharField(max_length=60)),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField()),
                ('valor_projeto', models.FloatField()),
                ('participante', models.CharField(max_length=150)),
            ],
        ),
    ]
